In [1]:
import pandas as pd
data=pd.read_csv("Dubai_scraped_data.csv")
print(data)

                                                     url bedrooms bathrooms  \
0      https://www.bayut.com/property/details-5613015...   4 Beds   5 Baths
1      https://www.bayut.com/property/details-7331267...    1 Bed   2 Baths
2      https://www.bayut.com/property/details-6935567...   7 Beds   7 Baths
3      https://www.bayut.com/property/details-6396763...    1 Bed   2 Baths
4      https://www.bayut.com/property/details-6932964...   2 Beds   3 Baths
...                                                  ...      ...       ...
73492  https://www.bayut.com/property/details-5526367...   2 Beds   3 Baths
73493  https://www.bayut.com/property/details-6067620...   2 Beds   3 Baths
73494  https://www.bayut.com/property/details-6067593...    1 Bed   2 Baths
73495  https://www.bayut.com/property/details-5136586...   2 Beds   2 Baths
73496  https://www.bayut.com/property/details-5008352...    1 Bed   2 Baths

         city                        location_1         location_2  \
0       Dubai                     Palm Jumeirah         Canal Cove
1       Dubai                    Downtown Dubai          The Lofts
2       Dubai                          Jumeirah         Jumeirah 2
3       Dubai                    Downtown Dubai           Old Town
4       Dubai                      Dubai Marina  Continental Tower
...       ...                               ...                ...
73492   Dubai                         Bur Dubai        Al Mankhool
73493   Dubai                       The Gardens        The Gardens
73494   Dubai   Jumeirah Village Triangle (JVT)     JVT District 5
73495   Dubai                         Al Barsha        Al Barsha 1
73496   Dubai                 Discovery Gardens        Zen Cluster

                                                 address       price  \
0      Canal Cove Frond G, Canal Cove, Palm Jumeirah,...  13,000,000
1       The Lofts East, The Lofts, Downtown Dubai, Dubai   2,000,000
2                            Jumeirah 2, Jumeirah, Dubai   7,600,000
3        Miska 5, Miska, Old Town, Downtown Dubai, Dubai   1,550,000
4                 Continental Tower, Dubai Marina, Dubai   1,800,000
...                                                  ...         ...
73492                      Al Mankhool, Bur Dubai, Dubai        7916
73493                                 The Gardens, Dubai        7291
73494  The Imperial Residence B, The Imperial Residen...        4000
73495                      Al Barsha 1, Al Barsha, Dubai        6666
73496              Zen Cluster, Discovery Gardens, Dubai        4166

             size         type       unit rent_or_sale web_name   source
0      5,060 sqft  Residential      Villa          Buy    bayut  scraped
1        745 sqft  Residential  Apartment          Buy    bayut  scraped
2      5,825 sqft  Residential      Villa          Buy    bayut  scraped
3        888 sqft  Residential  Apartment          Buy    bayut  scraped
4      1,396 sqft  Residential  Apartment          Buy    bayut  scraped
...           ...          ...        ...          ...      ...      ...
73492  1,205 sqft  Residential  Apartment         Rent    bayut  scraped
73493  1,450 sqft  Residential  Apartment         Rent    bayut  scraped
73494    800 sqft  Residential  Apartment         Rent    bayut  scraped
73495  1,450 sqft  Residential  Apartment         Rent    bayut  scraped
73496    980 sqft  Residential  Apartment         Rent    bayut  scraped

[73497 rows x 14 columns]

<ipython-input-1-9da502a547e6>:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv("Dubai_scraped_data.csv")

In [2]:
#Printing The DataFrame Without Extra Columns We Don't need
#data_subset= data[["url","bedrooms","bathrooms","city","location_1","location_2","address","price","size","type","unit","rent_or_sale" ]]
#print(data_subset)

In [3]:
#Missing Value Check
data.isna().sum()

url               0
bedrooms        431
bathrooms       625
city              0
location_1        0
location_2        0
address           0
price            16
size              4
type              0
unit              0
rent_or_sale      0
web_name          0
source            0
dtype: int64

In [4]:
data[data["size"].isna()]

,url,bedrooms,bathrooms,city,location_1,location_2,address,price,size,type,unit,rent_or_sale,web_name,source
2327,https://www.bayut.com/property/details-7333258...,3 Beds,3 Baths,Dubai,Jumeirah Village Circle (JVC),JVC District 13,"Levanto By Oro24, JVC District 13, Jumeirah Vi...","1,700,000",NaN,Residential,Apartment,Buy,bayut,scraped
2416,https://www.bayut.com/property/details-7339035...,3 Beds,4 Baths,Dubai,Town Square,Town Square,"Town Square, Dubai","1,780,000",NaN,Residential,Townhouse,Buy,bayut,scraped
5391,https://www.bayut.com/property/details-7303671...,3 Beds,4 Baths,Dubai,Mohammed Bin Rashid City,District 11,"The Fields, District 11, Mohammed Bin Rashid C...","3,000,000",NaN,Residential,Townhouse,Buy,bayut,scraped
33449,https://www.bayut.com/property/details-6992303...,2 Beds,2 Baths,Dubai,Arjan,Vincitore Benessere,"Vincitore Benessere, Arjan, Dubai","1,500,000",NaN,Residential,Apartment,Buy,bayut,scraped

In [5]:
data[data["bedrooms"].isna()]

,url,bedrooms,bathrooms,city,location_1,location_2,address,price,size,type,unit,rent_or_sale,web_name,source
280,https://www.bayut.com/property/details-6938046...,NaN,NaN,Dubai,Jumeirah Village Circle (JVC),JVC District 10,"JVC District 10, Jumeirah Village Circle (JVC)...","60,000,000","101,217 sqft",Residential,Residential Building,Buy,bayut,scraped
1078,https://www.bayut.com/property/details-6841828...,NaN,NaN,Dubai,Jebel Ali,Jebel Ali Hills,"Jebel Ali Hills, Jebel Ali, Dubai","1,500,000","11,042 sqft",Residential,Residential Plot,Buy,bayut,scraped
1388,https://www.bayut.com/property/details-6672916...,NaN,NaN,Dubai,Mohammed Bin Rashid City,Sobha Hartland,"Sobha Hartland, Mohammed Bin Rashid City, Dubai","7,100,000","7,354 sqft",Residential,Residential Plot,Buy,bayut,scraped
1399,https://www.bayut.com/property/details-7334461...,NaN,NaN,Dubai,Nad Al Sheba,Nad Al Sheba 1,"Nad Al Sheba 1, Nad Al Sheba, Dubai","3,800,000","5,003 sqft",Residential,Residential Plot,Buy,bayut,scraped
1658,https://www.bayut.com/property/details-6351860...,NaN,NaN,Dubai,Deira Island,Deira Island,"Deira Island, Dubai","16,500,000","64,230 sqft",Residential,Residential Plot,Buy,bayut,scraped
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42919,https://www.bayut.com/property/details-7017837...,NaN,NaN,Dubai,Dubai Hills Estate,Emerald Hills,"Emerald Hills, Dubai Hills Estate, Dubai","9,500,000","7,779 sqft",Residential,Residential Plot,Buy,bayut,scraped
42970,https://www.bayut.com/property/details-6802382...,NaN,NaN,Dubai,Dubai Residence Complex,Dubai Residence Complex,"Dubai Residence Complex, Dubai","6,500,000","71,410 sqft",Residential,Residential Plot,Buy,bayut,scraped
43020,https://www.bayut.com/property/details-6921701...,NaN,NaN,Dubai,Jumeirah Village Circle (JVC),Jumeirah Village Circle (JVC),"Jumeirah Village Circle (JVC), Dubai","16,500,000","163,000 sqft",Residential,Residential Plot,Buy,bayut,scraped
43096,https://www.bayut.com/property/details-6892820...,NaN,NaN,Dubai,Dubai Marina,Dubai Marina,"Dubai Marina, Dubai","249,000,000","330,159 sqft",Residential,Residential Building,Buy,bayut,scraped
43102,https://www.bayut.com/property/details-6863113...,NaN,NaN,Dubai,Jebel Ali,Jebel Ali Hills,"Jebel Ali Hills, Jebel Ali, Dubai","3,300,000","22,000 sqft",Residential,Residential Plot,Buy,bayut,scraped

In [6]:
data[data["bathrooms"].isna()]

,url,bedrooms,bathrooms,city,location_1,location_2,address,price,size,type,unit,rent_or_sale,web_name,source
280,https://www.bayut.com/property/details-6938046...,NaN,NaN,Dubai,Jumeirah Village Circle (JVC),JVC District 10,"JVC District 10, Jumeirah Village Circle (JVC)...","60,000,000","101,217 sqft",Residential,Residential Building,Buy,bayut,scraped
1078,https://www.bayut.com/property/details-6841828...,NaN,NaN,Dubai,Jebel Ali,Jebel Ali Hills,"Jebel Ali Hills, Jebel Ali, Dubai","1,500,000","11,042 sqft",Residential,Residential Plot,Buy,bayut,scraped
1147,https://www.bayut.com/property/details-7325692...,1 Bed,NaN,Dubai,Jumeirah Village Circle (JVC),JVC District 15,"Binghatti Onyx, JVC District 15, Jumeirah Vill...","799,000",664 sqft,Residential,Apartment,Buy,bayut,scraped
1253,https://www.bayut.com/property/details-6991810...,1 Bed,NaN,Dubai,Jumeirah Village Circle (JVC),JVC District 17,"Empire Residence, JVC District 17, Jumeirah Vi...","743,999",785 sqft,Residential,Apartment,Buy,bayut,scraped
1255,https://www.bayut.com/property/details-6992294...,1 Bed,NaN,Dubai,Jumeirah Village Circle (JVC),JVC District 17,"Empire Residence, JVC District 17, Jumeirah Vi...","746,999",785 sqft,Residential,Apartment,Buy,bayut,scraped
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43092,https://www.bayut.com/property/details-6907041...,3 Beds,NaN,Dubai,Downtown Dubai,Downtown Views II,"Downtown Views II, Downtown Dubai, Dubai","4,800,000","1,627 sqft",Residential,Apartment,Buy,bayut,scraped
43096,https://www.bayut.com/property/details-6892820...,NaN,NaN,Dubai,Dubai Marina,Dubai Marina,"Dubai Marina, Dubai","249,000,000","330,159 sqft",Residential,Residential Building,Buy,bayut,scraped
43102,https://www.bayut.com/property/details-6863113...,NaN,NaN,Dubai,Jebel Ali,Jebel Ali Hills,"Jebel Ali Hills, Jebel Ali, Dubai","3,300,000","22,000 sqft",Residential,Residential Plot,Buy,bayut,scraped
43160,https://www.bayut.com/property/details-6748796...,4 Beds,NaN,Dubai,Business Bay,Peninsula Four,"Peninsula Four, Business Bay, Dubai","14,842,000","5,438 sqft",Residential,Apartment,Buy,bayut,scraped
43189,https://www.bayut.com/property/details-6850180...,1 Bed,NaN,Dubai,Dubai Marina,LIV Lux,"LIV Lux, Dubai Marina, Dubai","2,489,548",833 sqft,Residential,Apartment,Buy,bayut,scraped

In [7]:
data[data["price"].isna()]

,url,bedrooms,bathrooms,city,location_1,location_2,address,price,size,type,unit,rent_or_sale,web_name,source
2042,https://www.bayut.com/property/details-7312780...,4 Beds,5 Baths,Dubai,Palm Jumeirah,The Crescent,"The Royal Atlantis Resort & Residences, The Cr...",NaN,"4,130 sqft",Residential,Apartment,Buy,bayut,scraped
6287,https://www.bayut.com/property/details-6807342...,3 Beds,5 Baths,Dubai,Palm Jumeirah,Oceana,"Oceana Aegean, Oceana, Palm Jumeirah, Dubai",NaN,"5,304 sqft",Residential,Penthouse,Buy,bayut,scraped
8708,https://www.bayut.com/property/details-6828376...,Studio,1 Bath,Dubai,Palm Jumeirah,The Palm Tower,"The Palm Tower, Palm Jumeirah, Dubai",NaN,524 sqft,Residential,Apartment,Buy,bayut,scraped
8709,https://www.bayut.com/property/details-5582755...,4 Beds,5 Baths,Dubai,Palm Jumeirah,Garden Homes Palm Jumeirah,"Garden Homes Frond L, Garden Homes Palm Jumeir...",NaN,"5,000 sqft",Residential,Villa,Buy,bayut,scraped
12177,https://www.bayut.com/property/details-6887919...,5 Beds,7 Baths,Dubai,Palm Jumeirah,Garden Homes Palm Jumeirah,"Garden Homes Frond N, Garden Homes Palm Jumeir...",NaN,"5,500 sqft",Residential,Villa,Buy,bayut,scraped
12178,https://www.bayut.com/property/details-7328438...,2 Beds,2 Baths,Dubai,Palm Jumeirah,W Residences,"Mansion 8, W Residences, Palm Jumeirah, Dubai",NaN,"1,237 sqft",Residential,Apartment,Buy,bayut,scraped
12179,https://www.bayut.com/property/details-6456291...,4 Beds,5 Baths,Dubai,Palm Jumeirah,Anantara Residences,"Anantara Residences - North, Anantara Residenc...",NaN,"10,587 sqft",Residential,Penthouse,Buy,bayut,scraped
12180,https://www.bayut.com/property/details-6812009...,3 Beds,4 Baths,Dubai,Palm Jumeirah,The Palm Beach Towers,"Palm Beach Tower 1, The Palm Beach Towers, Pal...",NaN,"2,830 sqft",Residential,Penthouse,Buy,bayut,scraped
20715,https://www.bayut.com/property/details-7016725...,1 Bed,2 Baths,Dubai,Palm Jumeirah,The Palm Tower,"The Palm Tower, Palm Jumeirah, Dubai",NaN,"1,035 sqft",Residential,Apartment,Buy,bayut,scraped
20716,https://www.bayut.com/property/details-6929325...,3 Beds,4 Baths,Dubai,Palm Jumeirah,FIVE Palm Jumeirah,"FIVE Palm Jumeirah, Palm Jumeirah, Dubai",NaN,"2,799 sqft",Residential,Apartment,Buy,bayut,scraped
20717,https://www.bayut.com/property/details-6811567...,2 Beds,3 Baths,Dubai,Palm Jumeirah,The Palm Beach Towers,"Palm Beach Tower 1, The Palm Beach Towers, Pal...",NaN,"1,670 sqft",Residential,Penthouse,Buy,bayut,scraped
20718,https://www.bayut.com/property/details-6518871...,6 Beds,6 Baths,Dubai,Al Jafiliya,Al Jafiliya,"Al Jafiliya, Dubai",NaN,"14,800 sqft",Residential,Villa,Buy,bayut,scraped
20719,https://www.bayut.com/property/details-6452706...,4 Beds,6 Baths,Dubai,Palm Jumeirah,Six Senses Residences,"Six Senses Residences, Palm Jumeirah, Dubai",NaN,"6,448 sqft",Residential,Villa,Buy,bayut,scraped
20720,https://www.bayut.com/property/details-5928620...,4 Beds,6 Baths,Dubai,Palm Jumeirah,One at Palm Jumeirah,"One at Palm Jumeirah, Palm Jumeirah, Dubai",NaN,"7,172 sqft",Residential,Penthouse,Buy,bayut,scraped
28387,https://www.bayut.com/property/details-6834239...,4 Beds,4 Baths,Dubai,Palm Jumeirah,One at Palm Jumeirah,"One at Palm Jumeirah, Palm Jumeirah, Dubai",NaN,"4,892 sqft",Residential,Apartment,Buy,bayut,scraped
28388,https://www.bayut.com/property/details-5937886...,4 Beds,5 Baths,Dubai,Palm Jumeirah,Kingdom Of Sheba,"Balqis Residence, Kingdom Of Sheba, Palm Jumei...",NaN,"7,100 sqft",Residential,Villa,Buy,bayut,scraped

In [8]:
data.describe()

,url,bedrooms,bathrooms,city,location_1,location_2,address,price,size,type,unit,rent_or_sale,web_name,source
count,73497,73066,72872,73497,73497,73497,73497,73481,73493,73497,73497,73497,73497,73497
unique,73494,19,20,1,229,1973,4193,8546,6325,1,9,2,1,1
top,https://www.bayut.com/property/details-6426754...,1 Bed,2 Baths,Dubai,Jumeirah Village Circle (JVC),JVC District 10,"Sun, Arabian Ranches 3, Dubai","2,500,000",850 sqft,Residential,Apartment,Buy,bayut,scraped
freq,2,20067,22063,73497,6115,1234,535,533,509,73497,53402,43276,73497,73497

In [9]:
#Checking Types of Data We have
data.dtypes

url             object
bedrooms        object
bathrooms       object
city            object
location_1      object
location_2      object
address         object
price           object
size            object
type            object
unit            object
rent_or_sale    object
web_name        object
source          object
dtype: object

In [10]:
#Change value buy to sale in column rent_or_sale
data.loc[data["rent_or_sale"]=="Buy","rent_or_sale"]="Sale"
#data

In [11]:
data["price"] = data["price"].str.replace(",", "").astype(float).astype("Int64")
data.dropna(subset=["price"], inplace=True)

In [12]:
data["price"].value_counts()

2500000     533
2200000     527
10000       505
2100000     499
2000000     477
           ...
1142568       1
4960000       1
28700000      1
763301        1
2075          1
Name: price, Length: 7895, dtype: Int64

In [13]:
import re
column_name = "size"

data[column_name] = data[column_name].apply(lambda x: re.sub(r'[a-zA-Z,]+', '', str(x)))

data[column_name] = pd.to_numeric(data[column_name], errors="coerce", downcast="integer")


data.dropna(subset=[column_name], inplace=True)

data[column_name] = data[column_name].astype(int)

In [14]:
data["size"].value_counts()

900     356
850     350
800     340
1400    316
1200    302
       ...
4563      1
8452      1
7534      1
4135      1
3531      1
Name: size, Length: 6214, dtype: int64

In [15]:
data.loc[data["bedrooms"]=="Studio", 'bedrooms'] = 1
data["bedrooms"]

0        4 Beds
1         1 Bed
2        7 Beds
3         1 Bed
4        2 Beds
          ...
65531     1 Bed
65532    3 Beds
65533    2 Beds
65534    5 Beds
65535    3 Beds
Name: bedrooms, Length: 65516, dtype: object

In [16]:


def extract_numeric_Values(value):
    try:
        return int(value.split()[0])
    except (AttributeError, ValueError):
        return None

data["bedrooms"] = data["bedrooms"].apply(extract_numeric_Values)
data["bathrooms"] = data["bathrooms"].apply(extract_numeric_Values)

data = data.dropna(subset=["bedrooms"])
data = data.dropna(subset=["bathrooms"])

data["bedrooms"] = data["bedrooms"].astype(int)
data["bathrooms"] = data["bathrooms"].astype(int)

In [17]:
data.dtypes

url             object
bedrooms         int64
bathrooms        int64
city            object
location_1      object
location_2      object
address         object
price            Int64
size             int64
type            object
unit            object
rent_or_sale    object
web_name        object
source          object
dtype: object

In [18]:
data

,url,bedrooms,bathrooms,city,location_1,location_2,address,price,size,type,unit,rent_or_sale,web_name,source
0,https://www.bayut.com/property/details-5613015...,4,5,Dubai,Palm Jumeirah,Canal Cove,"Canal Cove Frond G, Canal Cove, Palm Jumeirah,...",13000000,5060,Residential,Villa,Sale,bayut,scraped
1,https://www.bayut.com/property/details-7331267...,1,2,Dubai,Downtown Dubai,The Lofts,"The Lofts East, The Lofts, Downtown Dubai, Dubai",2000000,745,Residential,Apartment,Sale,bayut,scraped
2,https://www.bayut.com/property/details-6935567...,7,7,Dubai,Jumeirah,Jumeirah 2,"Jumeirah 2, Jumeirah, Dubai",7600000,5825,Residential,Villa,Sale,bayut,scraped
3,https://www.bayut.com/property/details-6396763...,1,2,Dubai,Downtown Dubai,Old Town,"Miska 5, Miska, Old Town, Downtown Dubai, Dubai",1550000,888,Residential,Apartment,Sale,bayut,scraped
4,https://www.bayut.com/property/details-6932964...,2,3,Dubai,Dubai Marina,Continental Tower,"Continental Tower, Dubai Marina, Dubai",1800000,1396,Residential,Apartment,Sale,bayut,scraped
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65531,https://www.bayut.com/property/details-6877931...,1,2,Dubai,International City,England Cluster,"England Cluster, International City, Dubai",2583,721,Residential,Apartment,Rent,bayut,scraped
65532,https://www.bayut.com/property/details-6856731...,3,4,Dubai,Dubai South,Emaar South,"Expo Golf Villas, Emaar South, Dubai South, Dubai",6500,2100,Residential,Villa,Rent,bayut,scraped
65533,https://www.bayut.com/property/details-6805432...,2,3,Dubai,Dubai Marina,Park Island,"Bonaire Tower, Park Island, Dubai Marina, Dubai",14583,1302,Residential,Apartment,Rent,bayut,scraped
65534,https://www.bayut.com/property/details-6775603...,5,6,Dubai,Umm Suqeim,Umm Suqeim 1,"Umm Suqeim 1, Umm Suqeim, Dubai",33333,5000,Residential,Villa,Rent,bayut,scraped
65535,https://www.bayut.com/property/details-6772749...,3,3,Dubai,Town Square,Hayat Townhouses,"Hayat Townhouses, Town Square, Dubai",10833,2023,Residential,Villa,Rent,bayut,scraped

In [19]:
#Checking for duplicates
duplicate_rows = data[data.duplicated()]
duplicate_rows

Empty DataFrame
Columns: [url, bedrooms, bathrooms, city, location_1, location_2, address, price, size, type, unit, rent_or_sale, web_name, source]
Index: []

In [22]:
data.to_csv("cleaned_dataset.csv", index=False, lineterminator='\r\n', sep=',', na_rep='', index_label=None)